//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnica_DigitalBank.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IUsuarioService")]
    public interface IUsuarioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Agregar", ReplyAction="http://tempuri.org/IUsuarioService/AgregarResponse")]
        bool Agregar(PruebaTecnica.Entities.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Agregar", ReplyAction="http://tempuri.org/IUsuarioService/AgregarResponse")]
        System.Threading.Tasks.Task<bool> AgregarAsync(PruebaTecnica.Entities.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Modificar", ReplyAction="http://tempuri.org/IUsuarioService/ModificarResponse")]
        bool Modificar(PruebaTecnica.Entities.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Modificar", ReplyAction="http://tempuri.org/IUsuarioService/ModificarResponse")]
        System.Threading.Tasks.Task<bool> ModificarAsync(PruebaTecnica.Entities.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Consultar", ReplyAction="http://tempuri.org/IUsuarioService/ConsultarResponse")]
        PruebaTecnica.Entities.Usuario[] Consultar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Consultar", ReplyAction="http://tempuri.org/IUsuarioService/ConsultarResponse")]
        System.Threading.Tasks.Task<PruebaTecnica.Entities.Usuario[]> ConsultarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Eliminar", ReplyAction="http://tempuri.org/IUsuarioService/EliminarResponse")]
        bool Eliminar(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Eliminar", ReplyAction="http://tempuri.org/IUsuarioService/EliminarResponse")]
        System.Threading.Tasks.Task<bool> EliminarAsync(int idUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioServiceChannel : PruebaTecnica_DigitalBank.ServiceReference.IUsuarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioServiceClient : System.ServiceModel.ClientBase<PruebaTecnica_DigitalBank.ServiceReference.IUsuarioService>, PruebaTecnica_DigitalBank.ServiceReference.IUsuarioService {
        
        public UsuarioServiceClient() {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Agregar(PruebaTecnica.Entities.Usuario usuario) {
            return base.Channel.Agregar(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarAsync(PruebaTecnica.Entities.Usuario usuario) {
            return base.Channel.AgregarAsync(usuario);
        }
        
        public bool Modificar(PruebaTecnica.Entities.Usuario usuario) {
            return base.Channel.Modificar(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarAsync(PruebaTecnica.Entities.Usuario usuario) {
            return base.Channel.ModificarAsync(usuario);
        }
        
        public PruebaTecnica.Entities.Usuario[] Consultar() {
            return base.Channel.Consultar();
        }
        
        public System.Threading.Tasks.Task<PruebaTecnica.Entities.Usuario[]> ConsultarAsync() {
            return base.Channel.ConsultarAsync();
        }
        
        public bool Eliminar(int idUsuario) {
            return base.Channel.Eliminar(idUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarAsync(int idUsuario) {
            return base.Channel.EliminarAsync(idUsuario);
        }
    }
}
